//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.NodejsTools.Repl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.NodejsTools.Repl.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops execution of the current command..
        /// </summary>
        internal static string cancelDescription {
            get {
                return ResourceManager.GetString("cancelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create Interactive window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - Black.
        /// </summary>
        internal static string ClassificationBlack {
            get {
                return ResourceManager.GetString("ClassificationBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - Blue.
        /// </summary>
        internal static string ClassificationBlue {
            get {
                return ResourceManager.GetString("ClassificationBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - Cyan.
        /// </summary>
        internal static string ClassificationCyan {
            get {
                return ResourceManager.GetString("ClassificationCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - Dark Blue.
        /// </summary>
        internal static string ClassificationDarkBlue {
            get {
                return ResourceManager.GetString("ClassificationDarkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - Dark Cyan.
        /// </summary>
        internal static string ClassificationDarkCyan {
            get {
                return ResourceManager.GetString("ClassificationDarkCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - Dark Gray.
        /// </summary>
        internal static string ClassificationDarkGray {
            get {
                return ResourceManager.GetString("ClassificationDarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - Dark Green.
        /// </summary>
        internal static string ClassificationDarkGreen {
            get {
                return ResourceManager.GetString("ClassificationDarkGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - Dark Magenta.
        /// </summary>
        internal static string ClassificationDarkMagenta {
            get {
                return ResourceManager.GetString("ClassificationDarkMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - Dark Red.
        /// </summary>
        internal static string ClassificationDarkRed {
            get {
                return ResourceManager.GetString("ClassificationDarkRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - Dark Yellow.
        /// </summary>
        internal static string ClassificationDarkYellow {
            get {
                return ResourceManager.GetString("ClassificationDarkYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - Error.
        /// </summary>
        internal static string ClassificationError {
            get {
                return ResourceManager.GetString("ClassificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - Gray.
        /// </summary>
        internal static string ClassificationGray {
            get {
                return ResourceManager.GetString("ClassificationGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - Green.
        /// </summary>
        internal static string ClassificationGreen {
            get {
                return ResourceManager.GetString("ClassificationGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - Magenta.
        /// </summary>
        internal static string ClassificationMagenta {
            get {
                return ResourceManager.GetString("ClassificationMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - Red.
        /// </summary>
        internal static string ClassificationRed {
            get {
                return ResourceManager.GetString("ClassificationRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - White.
        /// </summary>
        internal static string ClassificationWhite {
            get {
                return ResourceManager.GetString("ClassificationWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Interactive - Yellow.
        /// </summary>
        internal static string ClassificationYellow {
            get {
                return ResourceManager.GetString("ClassificationYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the contents of the REPL editor window..
        /// </summary>
        internal static string clearDescription {
            get {
                return ResourceManager.GetString("clearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppress or unsuppress output to the buffer..
        /// </summary>
        internal static string echoDescription {
            get {
                return ResourceManager.GetString("echoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECHO is {0}.
        /// </summary>
        internal static string echoState {
            get {
                return ResourceManager.GetString("echoState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a list of REPL commands..
        /// </summary>
        internal static string helpDescription {
            get {
                return ResourceManager.GetString("helpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to an empty execution engine, but keep REPL history..
        /// </summary>
        internal static string resetDescription {
            get {
                return ResourceManager.GetString("resetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for at least the specified number of milliseconds..
        /// </summary>
        internal static string waitDescription {
            get {
                return ResourceManager.GetString("waitDescription", resourceCulture);
            }
        }
    }
}
