//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodejsTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NodejsTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;seq&quot;:24,&quot;request_seq&quot;:13,&quot;type&quot;:&quot;response&quot;,&quot;command&quot;:&quot;backtrace&quot;,&quot;success&quot;:true,&quot;body&quot;:{&quot;fromFrame&quot;:0,&quot;toFrame&quot;:7,&quot;totalFrames&quot;:7,&quot;frames&quot;:[{&quot;type&quot;:&quot;frame&quot;,&quot;index&quot;:0,&quot;receiver&quot;:{&quot;ref&quot;:1,&quot;type&quot;:&quot;object&quot;,&quot;className&quot;:&quot;Object&quot;},&quot;func&quot;:{&quot;ref&quot;:0,&quot;type&quot;:&quot;function&quot;,&quot;name&quot;:&quot;&quot;,&quot;inferredName&quot;:&quot;&quot;,&quot;scriptId&quot;:33},&quot;script&quot;:{&quot;ref&quot;:12},&quot;constructCall&quot;:false,&quot;atReturn&quot;:false,&quot;debuggerFrame&quot;:false,&quot;arguments&quot;:[{&quot;name&quot;:&quot;exports&quot;,&quot;value&quot;:{&quot;ref&quot;:1,&quot;type&quot;:&quot;object&quot;,&quot;className&quot;:&quot;Object&quot;}},{&quot;name&quot;:&quot;require&quot;,&quot;value&quot;:{&quot;ref&quot;:6,&quot;type&quot; [rest of string wa....
        /// </summary>
        internal static string NodeBacktraceResponse {
            get {
                return ResourceManager.GetString("NodeBacktraceResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;name&quot;:&quot;v_boolean&quot;,&quot;value&quot;:{&quot;ref&quot;:21,&quot;type&quot;:&quot;boolean&quot;,&quot;value&quot;:false}}.
        /// </summary>
        internal static string NodeBacktraceVariableObject {
            get {
                return ResourceManager.GetString("NodeBacktraceVariableObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;value&quot;:{&quot;ref&quot;:21,&quot;type&quot;:&quot;boolean&quot;,&quot;value&quot;:false}}.
        /// </summary>
        internal static string NodeBacktraceVariableObjectWithoutName {
            get {
                return ResourceManager.GetString("NodeBacktraceVariableObjectWithoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;seq&quot;:11,&quot;type&quot;:&quot;event&quot;,&quot;event&quot;:&quot;break&quot;,&quot;body&quot;:{&quot;invocationText&quot;:&quot;#&lt;Object&gt;.[anonymous](exports=#&lt;Object&gt;, require=function require(path) {\n    return self.require(path);\n  }, module=#&lt;Module&gt;, __filename=C:\\Users\\Tester\\documents\\visual studio 2012\\Projects\\NodejsApp2\\NodejsApp2\\serv... (length: 85), __dirname=C:\\Users\\Tester\\documents\\visual studio 2012\\Projects\\NodejsApp2\\NodejsApp2)&quot;,&quot;sourceLine&quot;:1,&quot;sourceColumn&quot;:0,&quot;sourceLineText&quot;:&quot;var port = process.env.port || 1337;&quot;,&quot;script&quot;:{&quot;id&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NodeBreakpointResponse {
            get {
                return ResourceManager.GetString("NodeBreakpointResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;seq&quot;:5,&quot;type&quot;:&quot;event&quot;,&quot;event&quot;:&quot;afterCompile&quot;,&quot;success&quot;:true,&quot;body&quot;:{&quot;script&quot;:{&quot;handle&quot;:1,&quot;type&quot;:&quot;script&quot;,&quot;name&quot;:&quot;http.js&quot;,&quot;id&quot;:34,&quot;lineOffset&quot;:0,&quot;columnOffset&quot;:0,&quot;lineCount&quot;:2169,&quot;sourceStart&quot;:&quot;(function (exports, require, module, __filename, __dirname) { // Copyright Joyen&quot;,&quot;sourceLength&quot;:61850,&quot;scriptType&quot;:2,&quot;compilationType&quot;:0,&quot;context&quot;:{&quot;ref&quot;:0},&quot;text&quot;:&quot;http.js (lines: 2169)&quot;}},&quot;refs&quot;:[{&quot;handle&quot;:0,&quot;type&quot;:&quot;context&quot;,&quot;text&quot;:&quot;#&lt;ContextMirror&gt;&quot;}],&quot;running&quot;:true}.
        /// </summary>
        internal static string NodeCompileScriptResponse {
            get {
                return ResourceManager.GetString("NodeCompileScriptResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;seq&quot;: 1229,
        ///  &quot;type&quot;: &quot;event&quot;,
        ///  &quot;event&quot;: &quot;afterCompile&quot;,
        ///  &quot;success&quot;: true,
        ///  &quot;body&quot;: {
        ///    &quot;script&quot;: {
        ///      &quot;handle&quot;: 1,
        ///      &quot;type&quot;: &quot;script&quot;,
        ///      &quot;id&quot;: 172,
        ///      &quot;lineOffset&quot;: 0,
        ///      &quot;columnOffset&quot;: 0,
        ///      &quot;lineCount&quot;: 3,
        ///      &quot;sourceStart&quot;: &quot;(function() {\nvar ret = Buffer.prototype.writeUInt8.apply(this, arguments);this.&quot;,
        ///      &quot;sourceLength&quot;: 110,
        ///      &quot;scriptType&quot;: 2,
        ///      &quot;compilationType&quot;: 1,
        ///      &quot;evalFromScript&quot;: {
        ///        &quot;ref&quot;: 3
        ///      },
        ///      &quot;evalFromL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NodeCompileScriptResponseWithNullScriptName {
            get {
                return ResourceManager.GetString("NodeCompileScriptResponseWithNullScriptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{fullName: &quot;full name&quot;, age: 123}, {head:&quot;head&quot;, body:&quot;body&quot;}, [0, 1, 2]].
        /// </summary>
        internal static string NodeComplexArray {
            get {
                return ResourceManager.GetString("NodeComplexArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;seq&quot;:22,&quot;request_seq&quot;:10,&quot;type&quot;:&quot;response&quot;,&quot;command&quot;:&quot;disconnect&quot;,&quot;success&quot;:true,&quot;running&quot;:true}.
        /// </summary>
        internal static string NodeDisconnectResponse {
            get {
                return ResourceManager.GetString("NodeDisconnectResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;seq&quot;:21,&quot;request_seq&quot;:15,&quot;type&quot;:&quot;response&quot;,&quot;command&quot;:&quot;evaluate&quot;,&quot;success&quot;:true,&quot;body&quot;:{&quot;handle&quot;:16,&quot;type&quot;:&quot;string&quot;,&quot;value&quot;:&quot;&lt;tag&gt;Value&lt;/tag&gt;&quot;,&quot;length&quot;:16,&quot;text&quot;:&quot;&lt;tag&gt;Value&lt;/tag&gt;&quot;},&quot;refs&quot;:[],&quot;running&quot;:false}.
        /// </summary>
        internal static string NodeEvaluationResponse {
            get {
                return ResourceManager.GetString("NodeEvaluationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;handle&quot;:16,&quot;type&quot;:&quot;string&quot;,&quot;value&quot;:&quot;&lt;tag&gt;Value&lt;/tag&gt;&quot;,&quot;length&quot;:16,&quot;text&quot;:&quot;&lt;tag&gt;Value&lt;/tag&gt;&quot;}.
        /// </summary>
        internal static string NodeEvaluationVariableObject {
            get {
                return ResourceManager.GetString("NodeEvaluationVariableObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;seq&quot;:10,&quot;type&quot;:&quot;event&quot;,&quot;event&quot;:&quot;exception&quot;,&quot;success&quot;:true,&quot;body&quot;:{&quot;uncaught&quot;:false,&quot;exception&quot;:{&quot;handle&quot;:0,&quot;type&quot;:&quot;error&quot;,&quot;className&quot;:&quot;Error&quot;,&quot;constructorFunction&quot;:{&quot;ref&quot;:4},&quot;protoObject&quot;:{&quot;ref&quot;:5},&quot;prototypeObject&quot;:{&quot;ref&quot;:6},&quot;properties&quot;:[{&quot;name&quot;:&quot;stack&quot;,&quot;attributes&quot;:2,&quot;propertyType&quot;:3,&quot;ref&quot;:6},{&quot;name&quot;:&quot;arguments&quot;,&quot;attributes&quot;:2,&quot;propertyType&quot;:1,&quot;ref&quot;:6},{&quot;name&quot;:&quot;type&quot;,&quot;attributes&quot;:2,&quot;propertyType&quot;:1,&quot;ref&quot;:6},{&quot;name&quot;:&quot;message&quot;,&quot;attributes&quot;:2,&quot;propertyType&quot;:1,&quot;ref&quot;:7}],&quot;text&quot;:&quot;Error: Mission failed!&quot;},&quot;so [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NodeExceptionResponse {
            get {
                return ResourceManager.GetString("NodeExceptionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ref&quot;:4}.
        /// </summary>
        internal static string NodeLookupPrototypeObject {
            get {
                return ResourceManager.GetString("NodeLookupPrototypeObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;handle&quot;:2,&quot;type&quot;:&quot;function&quot;,&quot;className&quot;:&quot;Function&quot;,&quot;constructorFunction&quot;:{&quot;ref&quot;:56},&quot;protoObject&quot;:{&quot;ref&quot;:39},&quot;prototypeObject&quot;:{&quot;ref&quot;:4},&quot;name&quot;:&quot;Object&quot;,&quot;inferredName&quot;:&quot;&quot;,&quot;resolved&quot;:true,&quot;source&quot;:&quot;function Object() { [native code] }&quot;,&quot;scopes&quot;:[],&quot;properties&quot;:[{&quot;name&quot;:&quot;length&quot;,&quot;attributes&quot;:7,&quot;propertyType&quot;:3,&quot;ref&quot;:54},{&quot;name&quot;:&quot;name&quot;,&quot;attributes&quot;:7,&quot;propertyType&quot;:3,&quot;ref&quot;:57},{&quot;name&quot;:&quot;arguments&quot;,&quot;attributes&quot;:7,&quot;propertyType&quot;:3,&quot;ref&quot;:5},{&quot;name&quot;:&quot;caller&quot;,&quot;attributes&quot;:7,&quot;propertyType&quot;:3,&quot;ref&quot;:5},{&quot;name&quot;:&quot;proto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NodeLookupReferencesArray {
            get {
                return ResourceManager.GetString("NodeLookupReferencesArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;seq&quot;:15,&quot;request_seq&quot;:9,&quot;type&quot;:&quot;response&quot;,&quot;command&quot;:&quot;lookup&quot;,&quot;success&quot;:true,&quot;body&quot;:{&quot;25&quot;:{&quot;handle&quot;:25,&quot;type&quot;:&quot;object&quot;,&quot;className&quot;:&quot;Object&quot;,&quot;constructorFunction&quot;:{&quot;ref&quot;:2},&quot;protoObject&quot;:{&quot;ref&quot;:4},&quot;prototypeObject&quot;:{&quot;ref&quot;:3},&quot;properties&quot;:[{&quot;name&quot;:&quot;first&quot;,&quot;propertyType&quot;:1,&quot;ref&quot;:54},{&quot;name&quot;:&quot;second&quot;,&quot;propertyType&quot;:1,&quot;ref&quot;:55}],&quot;text&quot;:&quot;#&lt;Object&gt;&quot;}},&quot;refs&quot;:[{&quot;handle&quot;:2,&quot;type&quot;:&quot;function&quot;,&quot;className&quot;:&quot;Function&quot;,&quot;constructorFunction&quot;:{&quot;ref&quot;:56},&quot;protoObject&quot;:{&quot;ref&quot;:39},&quot;prototypeObject&quot;:{&quot;ref&quot;:4},&quot;name&quot;:&quot;Object&quot;,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NodeLookupResponse {
            get {
                return ResourceManager.GetString("NodeLookupResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;seq&quot;:7,&quot;request_seq&quot;:7,&quot;type&quot;:&quot;response&quot;,&quot;command&quot;:&quot;lookup&quot;,&quot;success&quot;:true,&quot;body&quot;:{&quot;9&quot;:{&quot;handle&quot;:9,&quot;type&quot;:&quot;string&quot;,&quot;value&quot;:&quot;ENOENT&quot;,&quot;length&quot;:6,&quot;text&quot;:&quot;ENOENT&quot;}},&quot;refs&quot;:[],&quot;running&quot;:false}.
        /// </summary>
        internal static string NodeLookupResponseWithPrimitiveObject {
            get {
                return ResourceManager.GetString("NodeLookupResponseWithPrimitiveObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;name&quot;:&quot;first&quot;,&quot;propertyType&quot;:1,&quot;ref&quot;:54}.
        /// </summary>
        internal static string NodeLookupVariableObject {
            get {
                return ResourceManager.GetString("NodeLookupVariableObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;seq&quot;:0,&quot;request_seq&quot;:1,&quot;type&quot;:&quot;response&quot;,&quot;command&quot;:&quot;scripts&quot;,&quot;success&quot;:true,&quot;body&quot;:[{&quot;handle&quot;:1,&quot;type&quot;:&quot;script&quot;,&quot;name&quot;:&quot;node.js&quot;,&quot;id&quot;:17,&quot;lineOffset&quot;:0,&quot;columnOffset&quot;:0,&quot;lineCount&quot;:903,&quot;sourceStart&quot;:&quot;// Copyright Joyent, Inc. and other Node contributors.\n//\n// Permission is hereb&quot;,&quot;sourceLength&quot;:28095,&quot;scriptType&quot;:2,&quot;compilationType&quot;:0,&quot;context&quot;:{&quot;ref&quot;:0},&quot;text&quot;:&quot;node.js (lines: 903)&quot;},{&quot;handle&quot;:3,&quot;type&quot;:&quot;script&quot;,&quot;name&quot;:&quot;path.js&quot;,&quot;id&quot;:22,&quot;lineOffset&quot;:0,&quot;columnOffset&quot;:0,&quot;lineCount&quot;:489,&quot;sourceStart&quot;:&quot;(fu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NodeScriptsResponse {
            get {
                return ResourceManager.GetString("NodeScriptsResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;seq&quot;:15,&quot;request_seq&quot;:9,&quot;type&quot;:&quot;response&quot;,&quot;command&quot;:&quot;setVariableValue&quot;,&quot;success&quot;:true,&quot;body&quot;:{&quot;newValue&quot;:{&quot;handle&quot;:44,&quot;type&quot;:&quot;number&quot;,&quot;value&quot;:55,&quot;text&quot;:&quot;55&quot;}},&quot;refs&quot;:[],&quot;running&quot;:false}.
        /// </summary>
        internal static string NodeSetVariableValueResponse {
            get {
                return ResourceManager.GetString("NodeSetVariableValueResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0, 1, 2].
        /// </summary>
        internal static string NodeSimpleArray {
            get {
                return ResourceManager.GetString("NodeSimpleArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {stringValue: &quot;stringValue&quot;, numberValue: 555, objectValue: {value: true}, arrayValue: [0, 1, 2]}.
        /// </summary>
        internal static string NodeVariable {
            get {
                return ResourceManager.GetString("NodeVariable", resourceCulture);
            }
        }
    }
}
