//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NodejsTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NodejsTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;seq&quot;:24,&quot;request_seq&quot;:13,&quot;type&quot;:&quot;response&quot;,&quot;command&quot;:&quot;backtrace&quot;,&quot;success&quot;:true,&quot;body&quot;:{&quot;fromFrame&quot;:0,&quot;toFrame&quot;:7,&quot;totalFrames&quot;:7,&quot;frames&quot;:[{&quot;type&quot;:&quot;frame&quot;,&quot;index&quot;:0,&quot;receiver&quot;:{&quot;ref&quot;:1,&quot;type&quot;:&quot;object&quot;,&quot;className&quot;:&quot;Object&quot;},&quot;func&quot;:{&quot;ref&quot;:0,&quot;type&quot;:&quot;function&quot;,&quot;name&quot;:&quot;&quot;,&quot;inferredName&quot;:&quot;&quot;,&quot;scriptId&quot;:33},&quot;script&quot;:{&quot;ref&quot;:12},&quot;constructCall&quot;:false,&quot;atReturn&quot;:false,&quot;debuggerFrame&quot;:false,&quot;arguments&quot;:[{&quot;name&quot;:&quot;exports&quot;,&quot;value&quot;:{&quot;ref&quot;:1,&quot;type&quot;:&quot;object&quot;,&quot;className&quot;:&quot;Object&quot;}},{&quot;name&quot;:&quot;require&quot;,&quot;value&quot;:{&quot;ref&quot;:6,&quot;type&quot; [rest of string wa....
        /// </summary>
        internal static string NodeBacktraceResponse {
            get {
                return ResourceManager.GetString("NodeBacktraceResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;name&quot;:&quot;v_boolean&quot;,&quot;value&quot;:{&quot;ref&quot;:21,&quot;type&quot;:&quot;boolean&quot;,&quot;value&quot;:false}}.
        /// </summary>
        internal static string NodeBacktraceVariableObject {
            get {
                return ResourceManager.GetString("NodeBacktraceVariableObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;value&quot;:{&quot;ref&quot;:21,&quot;type&quot;:&quot;boolean&quot;,&quot;value&quot;:false}}.
        /// </summary>
        internal static string NodeBacktraceVariableObjectWithoutName {
            get {
                return ResourceManager.GetString("NodeBacktraceVariableObjectWithoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{fullName: &quot;full name&quot;, age: 123}, {head:&quot;head&quot;, body:&quot;body&quot;}, [0, 1, 2]].
        /// </summary>
        internal static string NodeComplexArray {
            get {
                return ResourceManager.GetString("NodeComplexArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;seq&quot;:21,&quot;request_seq&quot;:15,&quot;type&quot;:&quot;response&quot;,&quot;command&quot;:&quot;evaluate&quot;,&quot;success&quot;:true,&quot;body&quot;:{&quot;handle&quot;:16,&quot;type&quot;:&quot;string&quot;,&quot;value&quot;:&quot;&lt;tag&gt;Value&lt;/tag&gt;&quot;,&quot;length&quot;:16,&quot;text&quot;:&quot;&lt;tag&gt;Value&lt;/tag&gt;&quot;},&quot;refs&quot;:[],&quot;running&quot;:false}.
        /// </summary>
        internal static string NodeEvaluationResponse {
            get {
                return ResourceManager.GetString("NodeEvaluationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;handle&quot;:16,&quot;type&quot;:&quot;string&quot;,&quot;value&quot;:&quot;&lt;tag&gt;Value&lt;/tag&gt;&quot;,&quot;length&quot;:16,&quot;text&quot;:&quot;&lt;tag&gt;Value&lt;/tag&gt;&quot;}.
        /// </summary>
        internal static string NodeEvaluationVariableObject {
            get {
                return ResourceManager.GetString("NodeEvaluationVariableObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ref&quot;:4}.
        /// </summary>
        internal static string NodeLookupPrototypeObject {
            get {
                return ResourceManager.GetString("NodeLookupPrototypeObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;handle&quot;:2,&quot;type&quot;:&quot;function&quot;,&quot;className&quot;:&quot;Function&quot;,&quot;constructorFunction&quot;:{&quot;ref&quot;:56},&quot;protoObject&quot;:{&quot;ref&quot;:39},&quot;prototypeObject&quot;:{&quot;ref&quot;:4},&quot;name&quot;:&quot;Object&quot;,&quot;inferredName&quot;:&quot;&quot;,&quot;resolved&quot;:true,&quot;source&quot;:&quot;function Object() { [native code] }&quot;,&quot;scopes&quot;:[],&quot;properties&quot;:[{&quot;name&quot;:&quot;length&quot;,&quot;attributes&quot;:7,&quot;propertyType&quot;:3,&quot;ref&quot;:54},{&quot;name&quot;:&quot;name&quot;,&quot;attributes&quot;:7,&quot;propertyType&quot;:3,&quot;ref&quot;:57},{&quot;name&quot;:&quot;arguments&quot;,&quot;attributes&quot;:7,&quot;propertyType&quot;:3,&quot;ref&quot;:5},{&quot;name&quot;:&quot;caller&quot;,&quot;attributes&quot;:7,&quot;propertyType&quot;:3,&quot;ref&quot;:5},{&quot;name&quot;:&quot;proto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NodeLookupReferencesArray {
            get {
                return ResourceManager.GetString("NodeLookupReferencesArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;seq&quot;:15,&quot;request_seq&quot;:9,&quot;type&quot;:&quot;response&quot;,&quot;command&quot;:&quot;lookup&quot;,&quot;success&quot;:true,&quot;body&quot;:{&quot;25&quot;:{&quot;handle&quot;:25,&quot;type&quot;:&quot;object&quot;,&quot;className&quot;:&quot;Object&quot;,&quot;constructorFunction&quot;:{&quot;ref&quot;:2},&quot;protoObject&quot;:{&quot;ref&quot;:4},&quot;prototypeObject&quot;:{&quot;ref&quot;:3},&quot;properties&quot;:[{&quot;name&quot;:&quot;first&quot;,&quot;propertyType&quot;:1,&quot;ref&quot;:54},{&quot;name&quot;:&quot;second&quot;,&quot;propertyType&quot;:1,&quot;ref&quot;:55}],&quot;text&quot;:&quot;#&lt;Object&gt;&quot;}},&quot;refs&quot;:[{&quot;handle&quot;:2,&quot;type&quot;:&quot;function&quot;,&quot;className&quot;:&quot;Function&quot;,&quot;constructorFunction&quot;:{&quot;ref&quot;:56},&quot;protoObject&quot;:{&quot;ref&quot;:39},&quot;prototypeObject&quot;:{&quot;ref&quot;:4},&quot;name&quot;:&quot;Object&quot;,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NodeLookupResponse {
            get {
                return ResourceManager.GetString("NodeLookupResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;name&quot;:&quot;first&quot;,&quot;propertyType&quot;:1,&quot;ref&quot;:54}.
        /// </summary>
        internal static string NodeLookupVariableObject {
            get {
                return ResourceManager.GetString("NodeLookupVariableObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0, 1, 2].
        /// </summary>
        internal static string NodeSimpleArray {
            get {
                return ResourceManager.GetString("NodeSimpleArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {stringValue: &quot;stringValue&quot;, numberValue: 555, objectValue: {value: true}, arrayValue: [0, 1, 2]}.
        /// </summary>
        internal static string NodeVariable {
            get {
                return ResourceManager.GetString("NodeVariable", resourceCulture);
            }
        }
    }
}
