//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.NodejsTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImportWizardResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportWizardResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.NodejsTools.ImportWizardResources", typeof(ImportWizardResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Back.
        /// </summary>
        public static string BackButtonLabel {
            get {
                return ResourceManager.GetString("BackButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to the folder containing your Node.js code.
        /// </summary>
        public static string BrowseNodeCodeAccessibleName {
            get {
                return ResourceManager.GetString("BrowseNodeCodeAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string CancelButtonLabel {
            get {
                return ResourceManager.GetString("CancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If it is not in this list, you can right-click any file in your project and choose &quot;Set as startup file&quot;.
        /// </summary>
        public static string F5FileSelectHelpText {
            get {
                return ResourceManager.GetString("F5FileSelectHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose which file to run when F5 is pressed..
        /// </summary>
        public static string F5FileSelectTitle {
            get {
                return ResourceManager.GetString("F5FileSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files with these extensions are included in the project..
        /// </summary>
        public static string FileFilterHelpText {
            get {
                return ResourceManager.GetString("FileFilterHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the filter for files to include.
        /// </summary>
        public static string FileFilterTitle {
            get {
                return ResourceManager.GetString("FileFilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Finish.
        /// </summary>
        public static string FinishButtonLabel {
            get {
                return ResourceManager.GetString("FinishButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files with a &apos;.js&apos;, or a &apos;.jsx&apos; extension, and &apos;jsconfig.json&apos; are automatically included..
        /// </summary>
        public static string JavaScriptHelpText {
            get {
                return ResourceManager.GetString("JavaScriptHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language this project primarily uses.
        /// </summary>
        public static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Next.
        /// </summary>
        public static string NextButtonLabel {
            get {
                return ResourceManager.GetString("NextButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file will be saved in the root of the folder that contains your Node.js code..
        /// </summary>
        public static string SaveFileLocationHelpText {
            get {
                return ResourceManager.GetString("SaveFileLocationHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name for your project.
        /// </summary>
        public static string SaveFileLocationTitle {
            get {
                return ResourceManager.GetString("SaveFileLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project.
        /// </summary>
        public static string SaveProjectPageTitle {
            get {
                return ResourceManager.GetString("SaveProjectPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We won&apos;t move any files from where they are now..
        /// </summary>
        public static string SelectNodeCodeHelpText {
            get {
                return ResourceManager.GetString("SelectNodeCodeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter or browse to the folder containing your Node.js code.
        /// </summary>
        public static string SelectNodeCodeTitle {
            get {
                return ResourceManager.GetString("SelectNodeCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Files.
        /// </summary>
        public static string SourceFilesPageTitle {
            get {
                return ResourceManager.GetString("SourceFilesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Files.
        /// </summary>
        public static string StartupPageTitle {
            get {
                return ResourceManager.GetString("StartupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files with a &apos;.ts&apos;, or a &apos;.tsx&apos; extension, and &apos;tsconfig.json&apos; are automatically included..
        /// </summary>
        public static string TypeScriptHelpText {
            get {
                return ResourceManager.GetString("TypeScriptHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Create New Project from Existing Node.js Code Wizard.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Project from Existing Node.js Code.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
