//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.NodejsTools.NpmUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NpmInstallWindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NpmInstallWindowResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.NodejsTools.NpmUI.NpmInstallWindowResources", typeof(NpmInstallWindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (recommended).
        /// </summary>
        public static string AddToPackageJsonCheckboxLabel {
            get {
                return ResourceManager.GetString("AddToPackageJsonCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to package.json.
        /// </summary>
        public static string AddToPackageJsonLabel {
            get {
                return ResourceManager.GetString("AddToPackageJsonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: .
        /// </summary>
        public static string AuthorLabel {
            get {
                return ResourceManager.GetString("AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Updated.
        /// </summary>
        public static string CatalogUpdatedMessage {
            get {
                return ResourceManager.GetString("CatalogUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string CloseButtonContent {
            get {
                return ResourceManager.GetString("CloseButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency type.
        /// </summary>
        public static string DependencyTypeLabel {
            get {
                return ResourceManager.GetString("DependencyTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string DevTypeDevelopmentChoice {
            get {
                return ResourceManager.GetString("DevTypeDevelopmentChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string DevTypeOptionalChoice {
            get {
                return ResourceManager.GetString("DevTypeOptionalChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string DevTypeStandardChoice {
            get {
                return ResourceManager.GetString("DevTypeStandardChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage: .
        /// </summary>
        public static string HomepageLabel {
            get {
                return ResourceManager.GetString("HomepageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed locally.
        /// </summary>
        public static string InstalledLocallyMessage {
            get {
                return ResourceManager.GetString("InstalledLocallyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Install Package.
        /// </summary>
        public static string InstallPackageButtonLabel {
            get {
                return ResourceManager.GetString("InstallPackageButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (latest).
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package missing.
        /// </summary>
        public static string MissingLocallyMessage {
            get {
                return ResourceManager.GetString("MissingLocallyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        public static string NoResultsFoundMessage {
            get {
                return ResourceManager.GetString("NoResultsFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old version.
        /// </summary>
        public static string OldVersionMessage {
            get {
                return ResourceManager.GetString("OldVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One result found.
        /// </summary>
        public static string OneResultFoundMessage {
            get {
                return ResourceManager.GetString("OneResultFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsLabel {
            get {
                return ResourceManager.GetString("OptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other npm arguments.
        /// </summary>
        public static string OtherNpmArgumentsLabel {
            get {
                return ResourceManager.GetString("OtherNpmArgumentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshButtonContent {
            get {
                return ResourceManager.GetString("RefreshButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Options.
        /// </summary>
        public static string ResetOptionsButtonLabel {
            get {
                return ResourceManager.GetString("ResetOptionsButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} results found.
        /// </summary>
        public static string ResultsFoundMessage {
            get {
                return ResourceManager.GetString("ResultsFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for packages.
        /// </summary>
        public static string SearchForPackagesLabel {
            get {
                return ResourceManager.GetString("SearchForPackagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type to search for packages..
        /// </summary>
        public static string SearchPromptMessage {
            get {
                return ResourceManager.GetString("SearchPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected version.
        /// </summary>
        public static string SelectedVersionLabel {
            get {
                return ResourceManager.GetString("SelectedVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install New npm Packages.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
