//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.NodejsTools.Profiling {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.NodejsTools.Profiling.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Baseline File:.
        /// </summary>
        public static string BaselineFileLabel {
            get {
                return ResourceManager.GetString("BaselineFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        public static string CancelButtonContent {
            get {
                return ResourceManager.GetString("CancelButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Line _Arguments:.
        /// </summary>
        public static string CommandLineArgumentsLabel {
            get {
                return ResourceManager.GetString("CommandLineArgumentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select analysis files for comparison.
        /// </summary>
        public static string CompareWindowTitle {
            get {
                return ResourceManager.GetString("CompareWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co_mparison File:.
        /// </summary>
        public static string ComparisionFileLabel {
            get {
                return ResourceManager.GetString("ComparisionFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build project, do you want to launch profiling anyway?.
        /// </summary>
        public static string FailedToBuild {
            get {
                return ResourceManager.GetString("FailedToBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open file {0}.
        /// </summary>
        public static string FailedToOpenFileErrorMessageText {
            get {
                return ResourceManager.GetString("FailedToOpenFileErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read performance session {0}.
        /// </summary>
        public static string FailedToReadPerformanceSessionMessageText {
            get {
                return ResourceManager.GetString("FailedToReadPerformanceSessionMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v8 log file was not successfully saved to:
        ///{0}
        ///
        ///No profiling data is available..
        /// </summary>
        public static string FailedToSaveV8LogMessageText {
            get {
                return ResourceManager.GetString("FailedToSaveV8LogMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project has no configured startup file, cannot start profiling..
        /// </summary>
        public static string NoConfiguredStatupFileErrorMessageText {
            get {
                return ResourceManager.GetString("NoConfiguredStatupFileErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.js Tools for Visual Studio.
        /// </summary>
        public static string NodejsToolsForVS {
            get {
                return ResourceManager.GetString("NodejsToolsForVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Node Path:.
        /// </summary>
        public static string NodePathLabel {
            get {
                return ResourceManager.GetString("NodePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Profiling Target.
        /// </summary>
        public static string NoProfilingConfiguredMessageCaption {
            get {
                return ResourceManager.GetString("NoProfilingConfiguredMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiling session is not configured - would you like to configure now and then launch?.
        /// </summary>
        public static string NoProfilingConfiguredMessageText {
            get {
                return ResourceManager.GetString("NoProfilingConfiguredMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string OkButtonContent {
            get {
                return ResourceManager.GetString("OkButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open project.
        /// </summary>
        public static string OpenProjectButton {
            get {
                return ResourceManager.GetString("OpenProjectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance report no longer exists: {0}.
        /// </summary>
        public static string PerformanceReportNoLongerExistsMessageText {
            get {
                return ResourceManager.GetString("PerformanceReportNoLongerExistsMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        public static string ProfilingOk {
            get {
                return ResourceManager.GetString("ProfilingOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to profile?.
        /// </summary>
        public static string ProfilingSettingsHeader {
            get {
                return ResourceManager.GetString("ProfilingSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiling Settings.
        /// </summary>
        public static string ProfilingSettingsTitle {
            get {
                return ResourceManager.GetString("ProfilingSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start.
        /// </summary>
        public static string ProfilingStart {
            get {
                return ResourceManager.GetString("ProfilingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project could not be found in current solution..
        /// </summary>
        public static string ProjectNotFoundErrorMessageText {
            get {
                return ResourceManager.GetString("ProjectNotFoundErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sc_ript:.
        /// </summary>
        public static string ScriptLabel {
            get {
                return ResourceManager.GetString("ScriptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_tandalone script.
        /// </summary>
        public static string StandaloneScriptLabel {
            get {
                return ResourceManager.GetString("StandaloneScriptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete &apos;{0}&apos;.
        ///
        ///There is probably a second copy of node.exe running
        ///and the results may be unavailable or incorrect..
        /// </summary>
        public static string UnableToDeleteV8Log {
            get {
                return ResourceManager.GetString("UnableToDeleteV8Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Working Directory:.
        /// </summary>
        public static string WorkingDirectoryLabel {
            get {
                return ResourceManager.GetString("WorkingDirectoryLabel", resourceCulture);
            }
        }
    }
}
